# Experiment 1 — Accuracy under mitigations

Rebuilds **Table 3** (CNN top-1 accuracy under NeuPerm vs. random noise, pruning
and quantization) and **Table 4** (Llama / Qwen SQuAD F1 + BoolQ accuracy)
directly from the canonical result CSVs shipped in `../results/`.

Data sources (see `../results/README.md`):
- `<model>_imagenet12.csv` (9 CNNs) — Table 3
- `llm_eval.csv` — Table 4 (SQuAD, BoolQ, WikiText-2)

In [1]:
import ast
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 30)

# Canonical result CSVs live in the repo's results/ dir.
RESULTS_DIR = Path("../results")

CNN_MODELS = [
    "densenet121", "resnet50", "resnet101", "vgg11", "vgg16",
    "efficientnet_b0", "efficientnet_b4", "mobilenet_v2", "mobilenet_v3_small",
]

MODEL_RENAME = {
    "densenet121": "DenseNet121", "resnet50": "ResNet50", "resnet101": "ResNet101",
    "vgg11": "VGG11", "vgg16": "VGG16", "mobilenet_v2": "MobileNetV2",
    "mobilenet_v3_small": "MobileNetV3-S",
    "efficientnet_b0": "EfficientNet-B0", "efficientnet_b4": "EfficientNet-B4",
}


def parse_kwargs(s):
    """method_kwargs is a stringified dict, e.g. "{'eps': 0.0001}"."""
    if isinstance(s, str) and s.strip():
        return ast.literal_eval(s)
    return {}


df_cnn = pd.concat(
    [pd.read_csv(RESULTS_DIR / f"{m}_imagenet12.csv") for m in CNN_MODELS],
    ignore_index=True,
)
df_cnn["kw"] = df_cnn["method_kwargs"].apply(parse_kwargs)
print(f"Loaded {len(df_cnn)} rows across {df_cnn['model_name'].nunique()} CNNs")
df_cnn.head()

Loaded 337 rows across 9 CNNs

    model_name  accuracy      time     dataset method    method_kwargs               kw
0  densenet121   0.74398  0.189444  imagenet12  noise  {'eps': 0.0001}  {'eps': 0.0001}
1  densenet121   0.74236  0.176961  imagenet12  noise   {'eps': 0.001}   {'eps': 0.001}
2  densenet121   0.28594  0.178190  imagenet12  noise    {'eps': 0.01}    {'eps': 0.01}
3  densenet121   0.00100  0.175615  imagenet12  noise     {'eps': 0.1}     {'eps': 0.1}
4  densenet121   0.74412  0.212567  imagenet12  noise  {'eps': 0.0001}  {'eps': 0.0001}

## Table 3 — CNN accuracy under mitigations

Per `(model, method)` mean±std top-1 accuracy. NeuPerm / noise / pruning are
multi-seed on the large models; `original` and quantization are single-shot.

In [2]:
acc_summary = (
    df_cnn.groupby(["model_name", "method"])["accuracy"]
    .agg(["mean", "std", "count"])
    .reset_index()
)
acc_summary

            model_name        method      mean       std  count
0          densenet121       neuperm  0.744374  0.000016     10
1          densenet121         noise  0.405326  0.346468     40
2          densenet121      original  0.744400       NaN      1
3          densenet121         prune  0.528776  0.176332     20
4          densenet121  quantization  0.332972  0.373032      5
5      efficientnet_b0       neuperm  0.776960  0.000057      2
6      efficientnet_b0         noise  0.616191  0.305888     11
7      efficientnet_b0      original  0.776980       NaN      1
8      efficientnet_b0         prune  0.199687  0.254419      6
9      efficientnet_b0  quantization  0.257013  0.443393      3
10     efficientnet_b4       neuperm  0.833980  0.000028      2
11     efficientnet_b4         noise  0.606304  0.388790     11
12     efficientnet_b4      original  0.833980       NaN      1
13     efficientnet_b4         prune  0.425567  0.408205      6
14     efficientnet_b4  quantization  0.279287  0.478408      3
15        mobilenet_v2       neuperm  0.721440  0.000020      3
16        mobilenet_v2         noise  0.454593  0.310548     12
17        mobilenet_v2      original  0.721480       NaN      1
18        mobilenet_v2         prune  0.039930  0.055523      6
19        mobilenet_v2  quantization  0.238060  0.410323      3
20  mobilenet_v3_small       neuperm  0.676767  0.000031      3
21  mobilenet_v3_small         noise  0.512125  0.264032     11
22  mobilenet_v3_small      original  0.676740       NaN      1
23  mobilenet_v3_small         prune  0.063653  0.117536      6
24  mobilenet_v3_small  quantization  0.220120  0.379579      3
25           resnet101       neuperm  0.819034  0.000037     10
26           resnet101         noise  0.404502  0.408252     40
27           resnet101      original  0.819020       NaN      1
28           resnet101         prune  0.457353  0.282042     20
29           resnet101  quantization  0.347148  0.429176      5
30            resnet50       neuperm  0.808426  0.000035     10
31            resnet50         noise  0.322519  0.368024     40
32            resnet50      original  0.808440       NaN      1
33            resnet50         prune  0.327762  0.312610     20
34            resnet50  quantization  0.321776  0.436602      5
35               vgg11       neuperm  0.690460       NaN      1
36               vgg11      original  0.690480       NaN      1
37               vgg11  quantization  0.395756  0.361169      5
38               vgg16       neuperm  0.715820       NaN      1
39               vgg16      original  0.715820       NaN      1
40               vgg16  quantization  0.423292  0.384153      5

### NeuPerm preserves accuracy

Headline claim: NeuPerm's functionally-equivalent permutation leaves top-1
accuracy essentially unchanged vs. `original`.

In [3]:
piv = (
    df_cnn[df_cnn["method"].isin(["original", "neuperm"])]
    .pivot_table(index="model_name", columns="method", values="accuracy", aggfunc="mean")
    .reindex(CNN_MODELS)
)
piv["delta"] = piv["neuperm"] - piv["original"]
piv.index = piv.index.map(MODEL_RENAME)
piv

method            neuperm  original         delta
model_name
DenseNet121      0.744374   0.74440 -2.600000e-05
ResNet50         0.808426   0.80844 -1.400000e-05
ResNet101        0.819034   0.81902  1.400000e-05
VGG11            0.690460   0.69048 -2.000000e-05
VGG16            0.715820   0.71582  0.000000e+00
EfficientNet-B0  0.776960   0.77698 -2.000000e-05
EfficientNet-B4  0.833980   0.83398 -1.110223e-16
MobileNetV2      0.721440   0.72148 -4.000000e-05
MobileNetV3-S    0.676767   0.67674  2.666667e-05

### Random-noise mitigation (by epsilon)

In [4]:
df_noise = df_cnn[df_cnn["method"] == "noise"].copy()
df_noise["eps"] = df_noise["kw"].apply(lambda d: d["eps"])
(
    df_noise.groupby(["model_name", "eps"])["accuracy"]
    .agg(["mean", "std"])
    .reset_index()
)

            model_name     eps      mean       std
0          densenet121  0.0001  0.744262  0.000296
1          densenet121  0.0010  0.741466  0.001425
2          densenet121  0.0100  0.134574  0.062366
3          densenet121  0.1000  0.001000  0.000000
4      efficientnet_b0  0.0001  0.777107  0.000064
5      efficientnet_b0  0.0010  0.776587  0.000367
6      efficientnet_b0  0.0100  0.705013  0.009971
7      efficientnet_b0  0.1000  0.000990  0.000099
8      efficientnet_b4  0.0001  0.833940  0.000057
9      efficientnet_b4  0.0010  0.834180  0.000334
10     efficientnet_b4  0.0100  0.832013  0.000699
11     efficientnet_b4  0.1000  0.000960  0.000131
12        mobilenet_v2  0.0001  0.721427  0.000232
13        mobilenet_v2  0.0010  0.719453  0.001021
14        mobilenet_v2  0.0100  0.376500  0.024804
15        mobilenet_v2  0.1000  0.000993  0.000167
16  mobilenet_v3_small  0.0001  0.676453  0.000270
17  mobilenet_v3_small  0.0010  0.674547  0.000471
18  mobilenet_v3_small  0.0100  0.526047  0.084082
19  mobilenet_v3_small  0.1000  0.001120  0.000057
20           resnet101  0.0001  0.818930  0.000125
21           resnet101  0.0010  0.795310  0.038281
22           resnet101  0.0100  0.002770  0.003277
23           resnet101  0.1000  0.001000  0.000000
24            resnet50  0.0001  0.808308  0.000105
25            resnet50  0.0010  0.479670  0.260018
26            resnet50  0.0100  0.001092  0.000278
27            resnet50  0.1000  0.001006  0.000060

### Pruning mitigation (by amount)

In [5]:
df_prune = df_cnn[df_cnn["method"] == "prune"].copy()
df_prune["amount"] = df_prune["kw"].apply(lambda d: d["amount"])
(
    df_prune.groupby(["model_name", "amount"])["accuracy"]
    .agg(["mean", "std"])
    .reset_index()
)

            model_name  amount      mean       std
0          densenet121    0.01  0.695960  0.014802
1          densenet121    0.05  0.361592  0.057529
2      efficientnet_b0    0.01  0.396893  0.212480
3      efficientnet_b0    0.05  0.002480  0.001640
4      efficientnet_b4    0.01  0.796267  0.008554
5      efficientnet_b4    0.05  0.054867  0.065183
6         mobilenet_v2    0.01  0.078467  0.057023
7         mobilenet_v2    0.05  0.001393  0.000403
8   mobilenet_v3_small    0.01  0.126187  0.151015
9   mobilenet_v3_small    0.05  0.001120  0.000260
10           resnet101    0.01  0.725004  0.034807
11           resnet101    0.05  0.189702  0.086773
12            resnet50    0.01  0.626532  0.085746
13            resnet50    0.05  0.028992  0.024350

### Quantization mitigation (by bit-width / per-channel)

In [6]:
df_quant = df_cnn[df_cnn["method"] == "quantization"].copy()
df_quant["n_bits"] = df_quant["kw"].apply(lambda d: d.get("n_bits"))
df_quant["per_channel"] = df_quant["kw"].apply(lambda d: d.get("per_channel"))
(
    df_quant.groupby(["model_name", "n_bits", "per_channel"])["accuracy"]
    .mean()
    .reset_index()
)

            model_name  n_bits  per_channel  accuracy
0          densenet121       2         True   0.00100
1          densenet121       4        False   0.00140
2          densenet121       4         True   0.19878
3          densenet121       8        False   0.72026
4          densenet121       8         True   0.74342
5      efficientnet_b0       2         True   0.00094
6      efficientnet_b0       4         True   0.00110
7      efficientnet_b0       8         True   0.76900
8      efficientnet_b4       2         True   0.00124
9      efficientnet_b4       4         True   0.00492
10     efficientnet_b4       8         True   0.83170
11        mobilenet_v2       2         True   0.00112
12        mobilenet_v2       4         True   0.00120
13        mobilenet_v2       8         True   0.71186
14  mobilenet_v3_small       2         True   0.00100
15  mobilenet_v3_small       4         True   0.00094
16  mobilenet_v3_small       8         True   0.65842
17           resnet101       2         True   0.00100
18           resnet101       4        False   0.00106
19           resnet101       4         True   0.10360
20           resnet101       8        False   0.81256
21           resnet101       8         True   0.81752
22            resnet50       2         True   0.00100
23            resnet50       4        False   0.00096
24            resnet50       4         True   0.00690
25            resnet50       8        False   0.79288
26            resnet50       8         True   0.80714
27               vgg11       2         True   0.00100
28               vgg11       4        False   0.00394
29               vgg11       4         True   0.59372
30               vgg11       8        False   0.69016
31               vgg11       8         True   0.68996
32               vgg16       2         True   0.00100
33               vgg16       4        False   0.00462
34               vgg16       4         True   0.67862
35               vgg16       8        False   0.71592
36               vgg16       8         True   0.71630

## Table 4 — LLM evaluation (SQuAD, BoolQ, WikiText-2)

`llm_eval.csv` holds 5-seed runs: SQuAD F1, BoolQ accuracy, and WikiText-2 perplexity for
Llama-3.2-1B and Qwen2.5-1.5B under each method. Mean±std over seeds.

In [7]:
df_llm = pd.read_csv(RESULTS_DIR / "llm_eval.csv")
llm_summary = (
    df_llm.groupby(["model", "benchmark", "method"])["score"]
    .agg(["mean", "std", "count"])
    .reset_index()
)
llm_summary

                    model  benchmark        method           mean            std  count
0   Llama-3.2-1B-Instruct      boolq          base      56.500000            NaN      1
1   Llama-3.2-1B-Instruct      boolq       neuperm      56.700000       0.908295      5
2   Llama-3.2-1B-Instruct      boolq         noise      29.250000      29.976526     20
3   Llama-3.2-1B-Instruct      boolq         prune      54.000000      13.840360     10
4   Llama-3.2-1B-Instruct      boolq  quantization      30.333333      23.468571     15
5   Llama-3.2-1B-Instruct      squad          base      77.050000            NaN      1
6   Llama-3.2-1B-Instruct      squad       neuperm      77.350000       0.458712      5
7   Llama-3.2-1B-Instruct      squad         noise      38.482605      39.503779     20
8   Llama-3.2-1B-Instruct      squad         prune      59.988102      15.128434     10
9   Llama-3.2-1B-Instruct      squad  quantization      34.890102      32.991482     15
10  Llama-3.2-1B-Instruct  wikitext2          base      12.368093            NaN      1
11  Llama-3.2-1B-Instruct  wikitext2       neuperm      12.368611       0.000927      5
12  Llama-3.2-1B-Instruct  wikitext2         noise      12.371714       0.005175      5
13  Llama-3.2-1B-Instruct  wikitext2         prune      14.249836       1.027835      5
14  Llama-3.2-1B-Instruct  wikitext2  quantization  324115.576531  474411.303758     15
15  Qwen2.5-1.5B-Instruct      boolq          base      74.500000            NaN      1
16  Qwen2.5-1.5B-Instruct      boolq       neuperm      74.600000       0.547723      5
17  Qwen2.5-1.5B-Instruct      boolq         noise      37.550000      38.175461     20
18  Qwen2.5-1.5B-Instruct      boolq         prune      69.700000       8.158840     10
19  Qwen2.5-1.5B-Instruct      boolq  quantization      25.000000      36.596253     15
20  Qwen2.5-1.5B-Instruct      squad          base      92.122826            NaN      1
21  Qwen2.5-1.5B-Instruct      squad       neuperm      92.089493       0.139443      5
22  Qwen2.5-1.5B-Instruct      squad         noise      45.933470      47.023418     20
23  Qwen2.5-1.5B-Instruct      squad         prune      69.249635      22.327857     10
24  Qwen2.5-1.5B-Instruct      squad  quantization      30.461224      44.312903     15
25  Qwen2.5-1.5B-Instruct  wikitext2          base       9.158964            NaN      1
26  Qwen2.5-1.5B-Instruct  wikitext2       neuperm       9.159402       0.000544      5
27  Qwen2.5-1.5B-Instruct  wikitext2         noise       9.161385       0.003656      5
28  Qwen2.5-1.5B-Instruct  wikitext2         prune      10.500186       0.357778      5
29  Qwen2.5-1.5B-Instruct  wikitext2  quantization  227544.734016  210260.549374     15

In [8]:
# Compact view: mean score per (model, benchmark) x method.
df_llm.pivot_table(
    index=["model", "benchmark"], columns="method", values="score", aggfunc="mean"
)

method                                base    neuperm      noise      prune   quantization
model                 benchmark
Llama-3.2-1B-Instruct boolq      56.500000  56.700000  29.250000  54.000000      30.333333
                      squad      77.050000  77.350000  38.482605  59.988102      34.890102
                      wikitext2  12.368093  12.368611  12.371714  14.249836  324115.576531
Qwen2.5-1.5B-Instruct boolq      74.500000  74.600000  37.550000  69.700000      25.000000
                      squad      92.122826  92.089493  45.933470  69.249635      30.461224
                      wikitext2   9.158964   9.159402   9.161385  10.500186  227544.734016